### PR TITLE
Fix #2818

### LINKED ISSUE #2818: `ApolloStore#writeAndPublish` overwrites cache entries when using nested fragments
**Summary**
When calling `writeAndPublish` for an `operation` that fetches part of the schema using graphql fragments, then the information saved in cache doesn't reflect passed `operationData`.

**Version**
2.4.6

**Description**
Context: We try to treat Apollo cache as a source of a truth, leveraing `ApolloStore#writeAndPublish` as a way to help Apollo cross-cache between queries or to i.e. fill incomplete data - basically we use it in edge cases, as a last resort.
I noticed that despite manually writing data to cache we still expecrience cache misses and unexpected api calls caused by a wrong cache state. I was able to narrow down the issue down to simple repro:

Given following schema:
```graphql
type Query {
  home: Home!
}

type Home {
  sectionA: SectionA
}

type SectionA {
  id: String!
  name: String!
  imageUrl: String
}
```
and a following query:
```graphql
query Home {
  home {
    ...sectionFragment
    sectionA {
      name
    }
  }
}

fragment sectionFragment on Home {
  sectionA {
    id
    imageUrl
  }
}
```
when following code invoked:
```kotlin
apolloStore.write(
      HomeQuery(),
      HomeQuery.Data(
        HomeQuery.Home(
          sectionA = HomeQuery.SectionA(
            name = "section-name"
          ),
          fragments = HomeQuery.Home.Fragments(
            sectionFragment = SectionFragment(
              sectionA = SectionFragment.SectionA(
                id = "section-id",
                imageUrl = "https://...",
              ),
            )
          )
        )
      )
    ).execute()
```
then cache gets filled with:
```
LruNormalizedCache {
  "section-id" : {
    "__typename" : SectionA
    "id" : section-id
    "imageUrl" : https://...
  }

  "QUERY_ROOT" : {
    "home" : CacheRecordRef(home)
  }

  "home" : {
    "__typename" : Home
    "sectionA" : CacheRecordRef(section-id)
  }
}
```

Expected result:
I'd expect the `name=section-name` to be saved under "section-id" cache key. 
```
  "section-id" : {
    "__typename" : SectionA
    "id" : section-id
    "imageUrl" : https://...
    "name" : section-name
  }

```

More context: 
 - From what I understood the issue appears here:
Screenshot 2020-12-24 at 00 25 26
where both `marshallers` write different parts of an objects under the same key.  
 - Obvious workaround would be to avoid using fragments if a query needs more fields than fragment already exposes.
- I was surprised when discovered mentioned `marshaller()` mechanism isn't used with network responses and they work in an expected way.

### PR DESCRIPTION
**Pull request by eduardb**
Following the suggestion from [here](https://github.com/apollographql/apollo-kotlin/issues/2818#issuecomment-750851549):
> A quick fix might be to do the merge in RealResponseWriter so that we do not overwrite the entries in buffer. The different values will come from different ResponseField but maybe it's not a big issue.

Also added an integration test based on the [reproducer](https://github.com/martinbonnin/apollo-android-samples/blob/main/reproducers/2818-fragment-overwrites/src/main/kotlin/main.kt), as suggested by @BoD (thank you!).

### CODE REVIEW

**Review by BoD — APPROVED** [review]
Looks good to me! Thanks a lot 🙏

File: apollo-integration/src/test/java/com/apollographql/apollo/FragmentOverwritesTest.kt [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+                )
+            ).execute()
+
+            val cacheResponse = apolloClient.query(HomeQuery())
+                .toBuilder()
+                .responseFetcher(ApolloResponseFetchers.CACHE_ONLY)
+                .build()
+                .await()
+
+            assertThat(cacheResponse.data?.home?.sectionA?.name).isEqualTo("modifiedSectionName")
```
Comment (martinbonnin) [inline apollo-integration/src/test/java/com/apollographql/apollo/FragmentOverwritesTest.kt:91]: Can you also add a check that the fragment is correctly written? 

```suggestion
            assertThat(cacheResponse.data?.home?.sectionA?.name).isEqualTo("modifiedSectionName")
            assertThat(cacheResponse.data?.home?.fragments?.sectionFragment?.sectionA?.imageUrl).isEqualTo("modifiedUrl")
```

**Review by martinbonnin — COMMENTED** [review]
A small comment but looks good to me, thanks!

File: apollo-integration/src/test/java/com/apollographql/apollo/FragmentOverwritesTest.kt (hunk 1 above)
Comment (eduardb) [reply apollo-integration/src/test/java/com/apollographql/apollo/FragmentOverwritesTest.kt:92]: Done in [0c04a41](https://github.com/apollographql/apollo-kotlin/pull/4358/commits/0c04a4174adcb11b66c82122faff6ad683df500c). Thanks!

**Comment by martinbonnin** [comment]
Thanks for the contribution!
