### PR TITLE
[validation] Normalize the order of arguments of checked definitions

### LINKED ISSUE #6648: migrating to registry.registerSchemaCodeGenerator() API surfaces unexpected directive behavior
### Version

4.3.1

### Summary

After migrating from 4.2.0 to 4.3.1 we get this cryptic error when using our customized ApolloCompilerPlugin:

schema.graphqls: (84465, 1): Apollo: Unexpected 'defer' definition. Expecting 'directive @defer (label: String, if: Boolean! = true) on FRAGMENT_SPREAD|INLINE_FRAGMENT'.

The schema does have this in it:
```
directive @defer ("Deferred behaviour is controlled by this argument" if: Boolean! = true, "A unique label that represents the fragment being deferred" label: String) on FRAGMENT_SPREAD|INLINE_FRAGMENT
```
But it should be valid...it's also defined in ApolloKotlin.graphql in this repo:
```
#
# @defer is not ratified yet in the GraphQL spec, but supported as an experimental feature in Apollo Kotlin
# Taken from https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-ast/src/main/resources/builtins.graphqls#L136
#

directive @defer(
  label: String
  if: Boolean! = true
) on FRAGMENT_SPREAD | INLINE_FRAGMENT
```

Is there anything else that has to be done to migrate to the new API?  I've looked through the closed issues and didn't see anything...

### Steps to reproduce the behavior

Old code:

```
   @ApolloExperimental
    override fun schemaListener(): SchemaListener {
        return object : SchemaListener {
            override fun onSchema(
                schema: Schema,
                outputDirectory: File,
            ) {
                if (generatePossibleTypes.isNotEmpty()) {
                    // Generate possible types for the given types, inside outputDirectory, based on schema.
                    ApolloSchemaPossibleTypesGenerator(
                        schema,
                        outputDirectory,
                        generatePossibleTypes,
                    ).generateSchema()
                }
            }
        }
    }
```

New code:
```
override fun beforeCompilationStep(
        environment: ApolloCompilerPluginEnvironment,
        registry: ApolloCompilerRegistry,
    ) {
        val possibleTypesGenerator = object : SchemaCodeGenerator {
            override fun generate(
                schema: GQLDocument,
                outputDirectory: File,
            ) {
                if (generatePossibleTypes.isNotEmpty()) {
                    // Generate possible types for the given types, inside outputDirectory, based on schema.
                    ApolloSchemaPossibleTypesGenerator(
                        schema.toSchema(),
                        outputDirectory,
                        generatePossibleTypes,
                    ).generateSchema()
                }
            }
        }
        registry.registerSchemaCodeGenerator(possibleTypesGenerator)
)
```

### Logs

```
schema.graphqls: (84465, 1): Apollo: Unexpected 'defer' definition. Expecting 'directive @defer (label: String, if: Boolean! = true) on FRAGMENT_SPREAD|INLINE_FRAGMENT'.
```

I think this happens in the schema.toSchema() call?

### PR DESCRIPTION
**Pull request by martinbonnin**
Fixes #6648

### CODE REVIEW

File: libraries/apollo-ast/src/commonMain/kotlin/com/apollographql/apollo/ast/internal/semanticEquals.kt [hunk 1]
```diff
@@ -11,18 +11,25 @@ internal fun GQLNode.semanticEquals(other: GQLNode?): Boolean {
...
+ * Two nodes with the same normalized representation behave the same during execution.
+ *
+ * Especially, descriptions are removed and field, inputFields, arguments, etc.. are sorted lexicographically.
+ */
 internal fun GQLNode.toSemanticSdl(): String {
   return transform2 { node ->
     when (node) {
       is GQLInputValueDefinition -> node.copy(description = null)
-      is GQLObjectTypeDefinition -> node.copy(description = null)
+      is GQLObjectTypeDefinition -> node.copy(description = null, fields = node.fields.sortedBy { it.name })
```
Comment (BoD) [inline libraries/apollo-ast/src/commonMain/kotlin/com/apollographql/apollo/ast/internal/semanticEquals.kt:25]: Should we also sort the `implementsInterfaces` and `directives` to be safe? (Does the order of directives count? 🤔)

Comment (martinbonnin) [reply libraries/apollo-ast/src/commonMain/kotlin/com/apollographql/apollo/ast/internal/semanticEquals.kt:25]: Yes, we should 👍 , adding this now

**Review by kenyee — APPROVED** [review]
Thanks for the quick fix!
And TIL how apollo checks for directive compatibility :-)
