### PR TITLE
Attempt at fixing a CI flake

### LINKED ISSUE #5965: Investigate serverCloseNicely flake

### PR DESCRIPTION
**Pull request by martinbonnin**
In case we receive a Close frame really quick, the coroutine could stay stucked on `receiveMessageChannel.receive()`.

I think this is a race in Ktor (see https://youtrack.jetbrains.com/issue/KTOR-7099/Race-condition-in-darwin-websockets-client-runIncomingProcessor). Adding a 1s delay seems to fix it.

Also took this opportunity to refactor a bit the error handling in `KtorWebSocketEngine`

Closes #5965

### CODE REVIEW

File: tests/engine/src/commonTest/kotlin/WebSocketEngineTest.kt [hunk 1]
```diff
@@ -100,6 +99,8 @@ class WebSocketEngineTest {
     val responseBody = webSocketServer.enqueueWebSocket()
     val connection = webSocketEngine.open(webSocketServer.url())
 
+    delay(1000)
```
Comment (martinbonnin) [inline tests/engine/src/commonTest/kotlin/WebSocketEngineTest.kt:102]: There is a bunch of refactoring in this PR but I believe this is the main fix. There seem to be a race condition in Ktor. I'm waiting for CI to pass and if everything looks good I'll open a youtrack.

**Review by BoD — APPROVED** [review]
🤞

**Comment by martinbonnin** [comment]
It just failed on `queriesAreBatchedByDefault` 😒 . That's a different flake than the `serverClosesNicely` so I'm just going to ignore that one for now....
