### PR TITLE
Fix inferred variables in both nullable and non-nullable locations

### LINKED ISSUE #4304: Fragment uses different types for variable: String, String!
### Summary
Optional type is required instead of non-optional.

A similar problem was with Int - https://github.com/apollographql/apollo-kotlin/issues/3768

### Version
Apollo 3.4.0

### Logs

Error:
`Fragment movieListFragment uses different types for variable 'mediaBillingTarget': String, String!`

Sample request:
```
query SomeMovies(
    $isTariffSubscriptionActive: Boolean!,
    $mediaBillingTarget: String!,
) {
    list {
        ... movieListFragment
    }
}

# Required optional and non-optional mediaBillingTarget: String(!)
fragment movieListFragment: MovieList {
    items {
        ... movieFragment
        ... movieTwoFragment
    }
}

fragment movieFragment: Movie {
    # Required optional mediaBillingTarget: String
    onlineViewOptions(mediaBillingTarget: $mediaBillingTarget) @skip(if: $isTariffSubscriptionActive) {
        ... onlineViewOptionShortFragment
    }
}

fragment movieTwoFragment: Movie {
    # Required non-optional mediaBillingTarget: String!
    viewOptions(mediaBillingTarget: $mediaBillingTarget) {
        ... onlineViewOptionShortFragment
    }
}
```

### PR DESCRIPTION
**Pull request by martinbonnin**
When the same fragment uses the same variable in both nullable and non-nullable locations, infer the variable type as non-nullable.
Closes #4304

### CODE REVIEW

File: apollo-compiler/src/main/kotlin/com/apollographql/apollo3/compiler/ir/IrBuilder.kt [hunk 1]
```diff
@@ -395,24 +395,24 @@ internal class IrBuilder(
...
 
-  private fun VariableUsage.toIr(): IrVariable {
-    var type = locationType.toIr()
-    // This is an inferred variable from a fragment
-    if (locationType !is GQLNonNullType) {
-      type = type.makeOptional()
+  private fun InferredVariable.toIr(): IrVariable {
+    var irType = type.toIr()
+    if (type !is GQLNonNullType) {
+      // If the location is non-nullable, the variable might be omitted, make it optional
```
Comment (BoD) [inline apollo-compiler/src/main/kotlin/com/apollographql/apollo3/compiler/ir/IrBuilder.kt:409]:
```suggestion
      // If the type is nullable, the variable might be omitted, make it optional
```

**Review by BoD — APPROVED** [review]
👍
