### PR TITLE
[gradle-plugin] Use lazy APIs

### LINKED ISSUE #5922: Apply com.apollographql.apollo3 plugin will break the dependencies in Kotlin Multiplatform according to IDEA
### Version

4.0.0-beta.6

### Summary

 When the plugin is applied, all dependencies used  in `commonMain` are not available in `commonTest`is applied

### Steps to reproduce the behavior

I created a repository with the documentation linked to the problem https://github.com/Hansanto/apollo-issue

### Logs

_No response_

### PR DESCRIPTION
**Pull request by martinbonnin**
Using `.any {}` was somewhat eagerly configuring things and that messed up KGP.

Fixes #5922

### CODE REVIEW

File: libraries/apollo-gradle-plugin-external/src/main/kotlin/com/apollographql/apollo3/gradle/internal/DefaultApolloExtension.kt [hunk 1]
```diff
@@ -600,7 +601,7 @@ abstract class DefaultApolloExtension(
         codegenMetadataConsumerConfiguration.dependencies.add(it)
       }
 
-      val pending = pendingDownstreamDependencies.get(name)
+      val pending = pendingDownstreamDependencies.get(service.name)
```
Comment (martinbonnin) [inline libraries/apollo-gradle-plugin-external/src/main/kotlin/com/apollographql/apollo3/gradle/internal/DefaultApolloExtension.kt:604]: This is an unrelated fix that I discovered by serendipity for `isADependencyOf(bidirectional: true)`

**Review by BoD — APPROVED** [review]
👏
